/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function gen(a: number, b: number, c: number, d: number): void;
export function __wbg_ret_free(a: number): void;
export function __wbg_get_ret_score(a: number): number;
export function __wbg_set_ret_score(a: number, b: number): void;
export function __wbg_get_ret_err(a: number, b: number): void;
export function __wbg_set_ret_err(a: number, b: number, c: number): void;
export function __wbg_get_ret_svg(a: number, b: number): void;
export function __wbg_set_ret_svg(a: number, b: number, c: number): void;
export function __wbg_solinfo_free(a: number): void;
export function __wbg_get_solinfo_error(a: number, b: number): void;
export function __wbg_set_solinfo_error(a: number, b: number, c: number): void;
export function __wbg_get_solinfo_max_turn(a: number): number;
export function __wbg_set_solinfo_max_turn(a: number, b: number): void;
export function __wbg_visresult_free(a: number): void;
export function __wbg_get_visresult_svg(a: number, b: number): void;
export function __wbg_set_visresult_svg(a: number, b: number, c: number): void;
export function __wbg_get_visresult_income(a: number): number;
export function __wbg_set_visresult_income(a: number, b: number): void;
export function __wbg_get_visresult_action(a: number, b: number): void;
export function __wbg_set_visresult_action(a: number, b: number, c: number): void;
export function __wbg_get_visresult_comments(a: number, b: number): void;
export function __wbg_set_visresult_comments(a: number, b: number, c: number): void;
export function vis(a: number, b: number, c: number, d: number, e: number): number;
export function get_max_turn(a: number, b: number, c: number, d: number): number;
export function __wbg_get_solinfo_score(a: number): number;
export function __wbg_get_visresult_money(a: number): number;
export function __wbg_set_solinfo_svg(a: number, b: number, c: number): void;
export function __wbg_get_solinfo_svg(a: number, b: number): void;
export function __wbg_set_solinfo_score(a: number, b: number): void;
export function __wbg_set_visresult_money(a: number, b: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
